services:
  - type: web
    name: shimzy
    runtime: python
    buildCommand: "poetry install --no-dev"
    startCommand: "poetry run gunicorn --worker-class gevent --workers 4 --bind 0.0.0.0:$PORT app:app"
    envVars:
      FLASK_ENV: production
      FERNET_KEY: ${FERNET_KEY}  # Set this in Render's dashboard

